---
# .codacy.yml
engines:
  cppcheck:
    language: cpp
    enabled: true
    patterns:
      - performance
      - portability
      - style
      - warning
      - error
      - information
      - memleak
      - unusedFunction
    exclude_patterns: []
  
  clang-tidy:
    enabled: true
    language: cpp
    patterns:
      - bugprone
      - cert
      - cppcoreguidelines
      - modernize
      - performance
      - readability

metrics:
  complexity:
    cyclomatic:
      warning: 15
      error: 25
    cognitive:
      warning: 20
      error: 35
    max_function_length:
      warning: 100
      error: 200
    max_file_length:
      warning: 800
      error: 1500
    max_parameters:
      warning: 6
      error: 8
    max_nesting_depth:
      warning: 5
      error: 7

duplication:
  min_tokens: 20
  min_lines: 3

style:
  line_length: 120
  indent_size: 2
  naming_conventions:
    function: snake_case
    variable: snake_case
    class: PascalCase
    constant: UPPER_CASE
  enforce_braces: true
  trailing_whitespace: error

coverage:
  overall: 70
  per_file: 60
  branch_coverage: 65

exclude_paths:
  - plugins/**
  - themes/**
  - toolchain/*.py
  - vendor/**
  - build/**
  - docs/**