---
# .codacy.yml
engines:
  cppcheck:
    language: cpp
    enabled: true
    patterns:
      - performance
      - portability
      - style
      - memleak

metrics:
  complexity:
    cyclomatic:
      warning: 10
      error: 15
    cognitive:
      warning: 15
      error: 20
    max_function_length:
      warning: 100
      error: 200
    max_file_length:
      warning: 1000
      error: 1500

duplication:
  min_tokens: 30

style:
  line_length: 100
  indent_size: 2
  naming_conventions:
    function: snake_case
    variable: snake_case
    class: PascalCase
    constant: UPPER_CASE

coverage:
  overall: 80
  per_file: 70

exclude_patterns:
  - vendor/**
  - plugins/**
  - themes/**