/*
  completion_spec.cpp

  This file is part of cjsh, CJ's Shell

  MIT License

  Copyright (c) 2026 Caden Finley

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
*/

#include "completion_spec.h"

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <mutex>
#include <sstream>
#include <unordered_map>
#include <utility>

namespace completion_specs {
namespace {

constexpr const char kHeaderPrefix[] = "generated by cjsh from man page for ";
constexpr const char kFormatPrefix[] = "format: ";
constexpr const char kSummaryPrefix[] = "summary: ";
constexpr const char kPathPrefix[] = "path: ";

std::mutex g_provider_mutex;
std::unordered_map<std::string, DynamicCompletionProvider> g_dynamic_providers;
std::unordered_map<std::string, CommandDoc> g_registered_docs;

std::string normalize_provider_name(const std::string& name) {
    std::string normalized;
    normalized.reserve(name.size());
    for (char ch : name) {
        unsigned char uch = static_cast<unsigned char>(ch);
        if (std::isalnum(uch) != 0 || ch == '-' || ch == '_' || ch == '.') {
            normalized.push_back(static_cast<char>(std::tolower(uch)));
        }
    }
    return normalized;
}

std::string normalize_command_name(std::string name) {
    std::transform(name.begin(), name.end(), name.begin(),
                   [](unsigned char ch) { return static_cast<char>(std::tolower(ch)); });
    return name;
}

std::string encode_field(const std::string& value) {
    std::ostringstream encoded;
    encoded << std::uppercase << std::hex;
    for (unsigned char ch : value) {
        if (ch == '%' || ch == ',' || ch == '\t' || ch == '\n' || ch == '\r') {
            encoded << '%' << std::setw(2) << std::setfill('0') << static_cast<unsigned int>(ch);
        } else {
            encoded << static_cast<char>(ch);
        }
    }
    return encoded.str();
}

int hex_value(char ch) {
    if (ch >= '0' && ch <= '9')
        return ch - '0';
    if (ch >= 'a' && ch <= 'f')
        return 10 + ch - 'a';
    if (ch >= 'A' && ch <= 'F')
        return 10 + ch - 'A';
    return -1;
}

std::optional<std::string> decode_field(const std::string& value) {
    std::string decoded;
    decoded.reserve(value.size());
    for (std::size_t index = 0; index < value.size(); ++index) {
        if (value[index] != '%') {
            decoded.push_back(value[index]);
            continue;
        }
        if (index + 2 >= value.size())
            return std::nullopt;
        int high = hex_value(value[index + 1]);
        int low = hex_value(value[index + 2]);
        if (high < 0 || low < 0)
            return std::nullopt;
        decoded.push_back(static_cast<char>((high << 4) | low));
        index += 2;
    }
    return decoded;
}

std::string encode_list(const std::vector<std::string>& values) {
    std::ostringstream stream;
    for (std::size_t index = 0; index < values.size(); ++index) {
        if (index != 0)
            stream << ',';
        stream << encode_field(values[index]);
    }
    return stream.str();
}

std::optional<std::vector<std::string>> decode_list(const std::string& value) {
    std::vector<std::string> result;
    if (value.empty())
        return result;

    std::size_t start = 0;
    while (start <= value.size()) {
        std::size_t comma = value.find(',', start);
        std::string encoded =
            value.substr(start, comma == std::string::npos ? std::string::npos : comma - start);
        auto decoded = decode_field(encoded);
        if (!decoded.has_value())
            return std::nullopt;
        result.push_back(std::move(*decoded));
        if (comma == std::string::npos)
            break;
        start = comma + 1;
    }
    return result;
}

std::vector<std::string> split_tabs(const std::string& line) {
    std::vector<std::string> fields;
    std::size_t start = 0;
    while (start <= line.size()) {
        std::size_t tab = line.find('\t', start);
        fields.push_back(
            line.substr(start, tab == std::string::npos ? std::string::npos : tab - start));
        if (tab == std::string::npos)
            break;
        start = tab + 1;
    }
    return fields;
}

EntryKind entry_kind_from_code(const std::string& value) {
    if (value == "S")
        return EntryKind::Subcommand;
    if (value == "P")
        return EntryKind::Positional;
    return EntryKind::Option;
}

char entry_kind_code(EntryKind kind) {
    switch (kind) {
        case EntryKind::Subcommand:
            return 'S';
        case EntryKind::Positional:
            return 'P';
        case EntryKind::Option:
        default:
            return 'O';
    }
}

ValueRequirement parse_requirement(const std::string& value) {
    if (value == "required")
        return ValueRequirement::Required;
    if (value == "optional")
        return ValueRequirement::Optional;
    return ValueRequirement::None;
}

ValueType parse_value_type(const std::string& value) {
    if (value == "text")
        return ValueType::Text;
    if (value == "file")
        return ValueType::File;
    if (value == "directory")
        return ValueType::Directory;
    if (value == "enum")
        return ValueType::Enum;
    if (value == "command")
        return ValueType::Command;
    if (value == "branch")
        return ValueType::Branch;
    if (value == "process")
        return ValueType::Process;
    if (value == "custom")
        return ValueType::Custom;
    return ValueType::None;
}

ValueSeparator parse_separator(const std::string& value) {
    if (value == "equals")
        return ValueSeparator::Equals;
    if (value == "either")
        return ValueSeparator::Either;
    return ValueSeparator::Space;
}

bool parse_bool(const std::string& value) {
    return value == "1" || value == "true" || value == "yes";
}

std::size_t parse_index(const std::string& value) {
    if (value.empty())
        return 0;
    try {
        std::size_t consumed = 0;
        unsigned long parsed = std::stoul(value, &consumed, 10);
        if (consumed != value.size())
            return 0;
        return static_cast<std::size_t>(parsed);
    } catch (...) {
        return 0;
    }
}

CompletionEntry* find_subcommand(std::vector<CompletionEntry>& entries, const std::string& name) {
    auto it = std::find_if(entries.begin(), entries.end(), [&](const CompletionEntry& entry) {
        return entry.kind == EntryKind::Subcommand && entry_matches_token(entry, name);
    });
    return it == entries.end() ? nullptr : &*it;
}

void serialize_entries(std::ostringstream& stream, const std::vector<CompletionEntry>& entries,
                       std::vector<std::string>& scope) {
    for (const auto& entry : entries) {
        stream << "E\t" << entry_kind_code(entry.kind) << '\t' << encode_list(scope) << '\t'
               << encode_field(entry.text) << '\t' << encode_field(entry.description) << '\t'
               << encode_list(entry.aliases) << '\t'
               << value_requirement_name(entry.value.requirement) << '\t'
               << value_type_name(entry.value.type) << '\t' << encode_field(entry.value.name)
               << '\t' << encode_list(entry.value.choices) << '\t' << encode_list(entry.conflicts)
               << '\t' << encode_list(entry.dependencies) << '\t' << (entry.repeatable ? '1' : '0')
               << '\t' << (entry.deprecated ? '1' : '0') << '\t'
               << encode_field(entry.value.dynamic_provider) << '\t' << entry.positional_index
               << '\t' << (entry.variadic ? '1' : '0') << '\t'
               << value_separator_name(entry.value.separator) << '\n';

        if (entry.kind == EntryKind::Subcommand && !entry.children.empty()) {
            scope.push_back(entry.text);
            serialize_entries(stream, entry.children, scope);
            scope.pop_back();
        }
    }
}

}  // namespace

bool register_command_doc(const std::string& command, CommandDoc doc) {
    std::string normalized = normalize_command_name(command);
    if (normalized.empty())
        return false;
    std::lock_guard<std::mutex> lock(g_provider_mutex);
    g_registered_docs[normalized] = std::move(doc);
    return true;
}

bool unregister_command_doc(const std::string& command) {
    std::lock_guard<std::mutex> lock(g_provider_mutex);
    return g_registered_docs.erase(normalize_command_name(command)) != 0;
}

std::optional<CommandDoc> lookup_registered_command_doc(const std::string& command) {
    std::lock_guard<std::mutex> lock(g_provider_mutex);
    auto it = g_registered_docs.find(normalize_command_name(command));
    if (it == g_registered_docs.end())
        return std::nullopt;
    return it->second;
}

bool register_dynamic_completion_provider(const std::string& name,
                                          DynamicCompletionProvider provider) {
    std::string normalized = normalize_provider_name(name);
    if (normalized.empty() || !provider)
        return false;
    std::lock_guard<std::mutex> lock(g_provider_mutex);
    g_dynamic_providers[normalized] = std::move(provider);
    return true;
}

bool unregister_dynamic_completion_provider(const std::string& name) {
    std::lock_guard<std::mutex> lock(g_provider_mutex);
    return g_dynamic_providers.erase(normalize_provider_name(name)) != 0;
}

std::vector<DynamicCompletionCandidate> request_dynamic_completions(
    const std::string& name, const DynamicCompletionRequest& request) {
    DynamicCompletionProvider provider;
    {
        std::lock_guard<std::mutex> lock(g_provider_mutex);
        auto it = g_dynamic_providers.find(normalize_provider_name(name));
        if (it == g_dynamic_providers.end())
            return {};
        provider = it->second;
    }
    try {
        return provider(request);
    } catch (...) {
        return {};
    }
}

bool entry_matches_token(const CompletionEntry& entry, const std::string& token) {
    if (entry.text == token)
        return true;
    return std::find(entry.aliases.begin(), entry.aliases.end(), token) != entry.aliases.end();
}

std::vector<std::string> entry_names(const CompletionEntry& entry) {
    std::vector<std::string> names;
    if (!entry.text.empty())
        names.push_back(entry.text);
    for (const auto& alias : entry.aliases) {
        if (!alias.empty() && std::find(names.begin(), names.end(), alias) == names.end())
            names.push_back(alias);
    }
    return names;
}

std::string default_provider_for_value_type(ValueType type) {
    switch (type) {
        case ValueType::File:
            return "file";
        case ValueType::Directory:
            return "directory";
        case ValueType::Command:
            return "command";
        case ValueType::Branch:
            return "branch";
        case ValueType::Process:
            return "process";
        default:
            return {};
    }
}

const char* value_requirement_name(ValueRequirement requirement) {
    switch (requirement) {
        case ValueRequirement::Required:
            return "required";
        case ValueRequirement::Optional:
            return "optional";
        case ValueRequirement::None:
        default:
            return "none";
    }
}

const char* value_type_name(ValueType type) {
    switch (type) {
        case ValueType::Text:
            return "text";
        case ValueType::File:
            return "file";
        case ValueType::Directory:
            return "directory";
        case ValueType::Enum:
            return "enum";
        case ValueType::Command:
            return "command";
        case ValueType::Branch:
            return "branch";
        case ValueType::Process:
            return "process";
        case ValueType::Custom:
            return "custom";
        case ValueType::None:
        default:
            return "none";
    }
}

const char* value_separator_name(ValueSeparator separator) {
    switch (separator) {
        case ValueSeparator::Equals:
            return "equals";
        case ValueSeparator::Either:
            return "either";
        case ValueSeparator::Space:
        default:
            return "space";
    }
}

std::string serialize_command_doc(const std::string& command, const CommandDoc& doc) {
    std::ostringstream stream;
    stream << kHeaderPrefix << command << '\n';
    stream << kFormatPrefix << kCompletionSpecFormatVersion << '\n';
    stream << kSummaryPrefix << encode_field(doc.summary) << '\n';
    stream << kPathPrefix << encode_field(doc.executable_path) << '\n';
    std::vector<std::string> scope;
    serialize_entries(stream, doc.entries, scope);
    return stream.str();
}

std::optional<CommandDoc> parse_command_doc(const std::string& command,
                                            const std::string& contents) {
    std::istringstream stream(contents);
    std::string line;
    if (!std::getline(stream, line) || line != std::string(kHeaderPrefix) + command)
        return std::nullopt;

    CommandDoc doc;
    unsigned int format_version = 1;
    struct PendingEntry {
        std::vector<std::string> scope;
        CompletionEntry entry;
    };
    std::vector<PendingEntry> pending;

    while (std::getline(stream, line)) {
        if (line.empty())
            continue;
        if (line.rfind(kFormatPrefix, 0) == 0) {
            format_version = static_cast<unsigned int>(
                parse_index(line.substr(std::char_traits<char>::length(kFormatPrefix))));
            if (format_version == 0 || format_version > kCompletionSpecFormatVersion)
                return std::nullopt;
            continue;
        }
        if (line.rfind(kSummaryPrefix, 0) == 0) {
            std::string raw = line.substr(std::char_traits<char>::length(kSummaryPrefix));
            auto value = format_version >= 2 ? decode_field(raw)
                                             : std::optional<std::string>(std::move(raw));
            if (!value.has_value())
                return std::nullopt;
            doc.summary = std::move(*value);
            doc.summary_present = true;
            continue;
        }
        if (line.rfind(kPathPrefix, 0) == 0) {
            std::string raw = line.substr(std::char_traits<char>::length(kPathPrefix));
            auto value = format_version >= 2 ? decode_field(raw)
                                             : std::optional<std::string>(std::move(raw));
            if (!value.has_value())
                return std::nullopt;
            doc.executable_path = std::move(*value);
            continue;
        }

        auto fields = split_tabs(line);
        if (fields.size() >= 18 && fields[0] == "E") {
            auto scope = decode_list(fields[2]);
            auto text = decode_field(fields[3]);
            auto description = decode_field(fields[4]);
            auto aliases = decode_list(fields[5]);
            auto value_name = decode_field(fields[8]);
            auto choices = decode_list(fields[9]);
            auto conflicts = decode_list(fields[10]);
            auto dependencies = decode_list(fields[11]);
            auto provider = decode_field(fields[14]);
            if (!scope || !text || !description || !aliases || !value_name || !choices ||
                !conflicts || !dependencies || !provider) {
                return std::nullopt;
            }

            CompletionEntry entry;
            entry.kind = entry_kind_from_code(fields[1]);
            entry.text = std::move(*text);
            entry.description = std::move(*description);
            entry.aliases = std::move(*aliases);
            entry.value.requirement = parse_requirement(fields[6]);
            entry.value.type = parse_value_type(fields[7]);
            entry.value.name = std::move(*value_name);
            entry.value.choices = std::move(*choices);
            entry.conflicts = std::move(*conflicts);
            entry.dependencies = std::move(*dependencies);
            entry.repeatable = parse_bool(fields[12]);
            entry.deprecated = parse_bool(fields[13]);
            entry.value.dynamic_provider = std::move(*provider);
            entry.positional_index = parse_index(fields[15]);
            entry.variadic = parse_bool(fields[16]);
            entry.value.separator = parse_separator(fields[17]);
            pending.push_back({std::move(*scope), std::move(entry)});
            continue;
        }

        // Version 1 compatibility: <O|S|P> TAB value TAB description.
        if (fields.size() >= 3 && fields[0].size() == 1) {
            CompletionEntry entry;
            entry.kind = entry_kind_from_code(fields[0]);
            entry.text = fields[1];
            entry.description = fields[2];
            entry.repeatable = true;  // The old format had no repeatability semantics.
            pending.push_back({{}, std::move(entry)});
        }
    }

    std::stable_sort(pending.begin(), pending.end(),
                     [](const PendingEntry& lhs, const PendingEntry& rhs) {
                         return lhs.scope.size() < rhs.scope.size();
                     });
    for (auto& item : pending) {
        std::vector<CompletionEntry>* entries = &doc.entries;
        bool valid_scope = true;
        for (const auto& component : item.scope) {
            CompletionEntry* parent = find_subcommand(*entries, component);
            if (parent == nullptr) {
                valid_scope = false;
                break;
            }
            entries = &parent->children;
        }
        if (valid_scope)
            entries->push_back(std::move(item.entry));
    }

    doc.summary_present = true;
    return doc;
}

}  // namespace completion_specs
