#include "suggestion_utils.h"

#include <algorithm>
#include <filesystem>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace suggestion_utils {

std::vector<std::string> generate_command_suggestions(const std::string& command) {
    std::vector<std::string> suggestions;
    
    // Common typos and alternative commands
    static const std::unordered_map<std::string, std::vector<std::string>> common_typos = {
        {"sl", {"ls"}},
        {"ll", {"ls -l"}},
        {"la", {"ls -la"}}, 
        {"ks", {"ls"}},
        {"s", {"ls"}},
        {"dir", {"ls"}},
        {"cls", {"clear"}},
        {"cat", {"cat"}},
        {"ehco", {"echo"}},
        {"eco", {"echo"}},
        {"exot", {"exit"}},
        {"eixt", {"exit"}},
        {"quit", {"exit"}},
        {"clea", {"clear"}},
        {"clera", {"clear"}},
        {"celar", {"clear"}},
        {"grpe", {"grep"}},
        {"gerp", {"grep"}},
        {"greb", {"grep"}},
        {"mdir", {"mkdir"}},
        {"mkidr", {"mkdir"}},
        {"mkdr", {"mkdir"}},
        {"rmdir", {"rmdir"}},
        {"rmdr", {"rmdir"}},
        {"rmdri", {"rmdir"}},
        {"whcih", {"which"}},
        {"wich", {"which"}},
        {"whic", {"which"}},
        {"sudp", {"sudo"}},
        {"sduo", {"sudo"}},
        {"suod", {"sudo"}},
        {"pign", {"ping"}},
        {"pinf", {"ping"}},
        {"crul", {"curl"}},
        {"curk", {"curl"}},
        {"cusl", {"curl"}},
        {"wgte", {"wget"}},
        {"wetg", {"wget"}},
        {"vmi", {"vim"}},
        {"ivm", {"vim"}},
        {"vmi", {"vim"}},
        {"emacs", {"emacs"}},
        {"nano", {"nano"}},
        {"pico", {"nano"}},
        {"tial", {"tail"}},
        {"iatl", {"tail"}},
        {"haed", {"head"}},
        {"hedh", {"head"}},
        {"tarr", {"tar"}},
        {"tra", {"tar"}},
        {"unizp", {"unzip"}},
        {"uzinp", {"unzip"}},
        {"zipu", {"unzip"}},
        {"gizp", {"gzip"}},
        {"gpzi", {"gzip"}},
        {"gunizp", {"gunzip"}},
        {"guzinp", {"gunzip"}},
        {"fdin", {"find"}},
        {"ifnd", {"find"}},
        {"findd", {"find"}},
        {"locat", {"locate"}},
        {"locaet", {"locate"}},
        {"duf", {"du"}},
        {"ud", {"du"}},
        {"fd", {"df"}},
        {"dff", {"df"}},
        {"sp", {"ps"}},
        {"pss", {"ps"}},
        {"kil", {"kill"}},
        {"killl", {"kill"}},
        {"killal", {"killall"}},
        {"kilall", {"killall"}},
        {"topx", {"top"}},
        {"pot", {"top"}},
        {"htpo", {"htop"}},
        {"hotp", {"htop"}},
        {"frep", {"free"}},
        {"fere", {"free"}},
        {"uptiem", {"uptime"}},
        {"uptmie", {"uptime"}},
        {"whoa", {"whoami"}},
        {"whomai", {"whoami"}},
        {"whami", {"whoami"}},
        {"daet", {"date"}},
        {"dtae", {"date"}},
        {"cla", {"cal"}},
        {"acl", {"cal"}},
        {"hisotry", {"history"}},
        {"hsitory", {"history"}},
        {"histroy", {"history"}},
        {"alias", {"alias"}},
        {"aliass", {"alias"}},
        {"unaials", {"unalias"}},
        {"unalais", {"unalias"}},
        {"sourc", {"source"}},
        {"soruce", {"source"}},
        {"basrh", {"bash"}},
        {"ahsb", {"bash"}},
        {"zhs", {"zsh"}},
        {"hzs", {"zsh"}},
        {"fishh", {"fish"}},
        {"hsif", {"fish"}},
        {"tsch", {"tcsh"}},
        {"hcts", {"tcsh"}},
        {"ksh", {"ksh"}},
        {"hsk", {"ksh"}},
        {"dash", {"dash"}},
        {"hasd", {"dash"}},
        {"shh", {"ssh"}},
        {"hss", {"ssh"}},
        {"scp", {"scp"}},
        {"pcs", {"scp"}},
        {"rsyn", {"rsync"}},
        {"rscyn", {"rsync"}},
        {"synrc", {"rsync"}},
        {"ftpp", {"ftp"}},
        {"tpf", {"ftp"}},
        {"telnett", {"telnet"}},
        {"telent", {"telnet"}},
        {"ncatt", {"ncat"}},
        {"netcatt", {"netcat"}},
        {"netcta", {"netcat"}},
        {"cutt", {"cut"}},
        {"tuc", {"cut"}},
        {"awwk", {"awk"}},
        {"kwa", {"awk"}},
        {"sedd", {"sed"}},
        {"des", {"sed"}},
        {"sortt", {"sort"}},
        {"tros", {"sort"}},
        {"uniqq", {"uniq"}},
        {"qinu", {"uniq"}},
        {"trr", {"tr"}},
        {"rt", {"tr"}},
        {"wcc", {"wc"}},
        {"cw", {"wc"}},
        {"diffff", {"diff"}},
        {"fidd", {"diff"}},
        {"comm", {"comm"}},
        {"momc", {"comm"}},
        {"joinn", {"join"}},
        {"nioj", {"join"}},
        {"pastte", {"paste"}},
        {"tsaep", {"paste"}},
        {"expandd", {"expand"}},
        {"dnapxe", {"expand"}},
        {"unexpandd", {"unexpand"}},
        {"dnapxenu", {"unexpand"}},
        {"foldd", {"fold"}},
        {"dlof", {"fold"}},
        {"fmtt", {"fmt"}},
        {"tmf", {"fmt"}},
        {"prr", {"pr"}},
        {"rp", {"pr"}},
        {"nlll", {"nl"}},
        {"ln", {"ln"}},
        {"nl", {"nl"}},
        {"spiltt", {"split"}},
        {"tilps", {"split"}},
        {"joinnn", {"join"}},
        {"niojj", {"join"}},
        {"csplitt", {"csplit"}},
        {"tilpsc", {"csplit"}},
        {"shufss", {"shuf"}},
        {"fuhs", {"shuf"}},
        {"factorr", {"factor"}},
        {"rotcaf", {"factor"}},
        {"seqq", {"seq"}},
        {"qes", {"seq"}},
        {"shreddd", {"shred"}},
        {"derhs", {"shred"}},
        {"sunn", {"sum"}},
        {"mus", {"sum"}},
        {"cksunn", {"cksum"}},
        {"muskc", {"cksum"}},
        {"md5summ", {"md5sum"}},
        {"musd5m", {"md5sum"}},
        {"sha1summ", {"sha1sum"}},
        {"musha1s", {"sha1sum"}},
        {"sha256summ", {"sha256sum"}},
        {"musha256s", {"sha256sum"}},
        {"sha512summ", {"sha512sum"}},
        {"musha512s", {"sha512sum"}},
        {"b2summ", {"b2sum"}},
        {"musb2", {"b2sum"}},
        {"base32", {"base32"}},
        {"23esab", {"base32"}},
        {"base64", {"base64"}},
        {"46esab", {"base64"}},
        {"basenccc", {"basenc"}},
        {"cnesab", {"basenc"}},
        {"uuencodee", {"uuencode"}},
        {"edocnuu", {"uuencode"}},
        {"uudecode", {"uudecode"}},
        {"edocduu", {"uudecode"}},
        {"ptxx", {"ptx"}},
        {"xtp", {"ptx"}},
        {"tsacc", {"tsac"}},
        {"cats", {"tac"}},
        {"revv", {"rev"}},
        {"ver", {"rev"}},
        {"pastee", {"paste"}},
        {"etsap", {"paste"}},
        {"joinnn", {"join"}},
        {"niojj", {"join"}},
        {"commmm", {"comm"}},
        {"mmoc", {"comm"}},
        {"uniqqqq", {"uniq"}},
        {"qinuu", {"uniq"}},
        {"sortttt", {"sort"}},
        {"tross", {"sort"}},
        {"shufffff", {"shuf"}},
        {"fuhss", {"shuf"}},
        {"nll", {"nl"}},
        {"lnnn", {"ln"}},
        {"factorrr", {"factor"}},
        {"rotcaff", {"factor"}},
        {"seqqq", {"seq"}},
        {"qess", {"seq"}},
        {"exprr", {"expr"}},
        {"rpxe", {"expr"}},
        {"testt", {"test"}},
        {"tset", {"test"}},
        {"truee", {"true"}},
        {"eurt", {"true"}},
        {"falsee", {"false"}},
        {"eslaf", {"false"}},
        {"yess", {"yes"}},
        {"sey", {"yes"}},
        {"printff", {"printf"}},
        {"ftnirp", {"printf"}},
        {"echooo", {"echo"}},
        {"ohce", {"echo"}},
        {"sleeppp", {"sleep"}},
        {"peels", {"sleep"}},
        {"timeoutttt", {"timeout"}},
        {"tuoemit", {"timeout"}},
        {"runuserrrr", {"runuser"}},
        {"resunur", {"runuser"}},
        {"suu", {"su"}},
        {"us", {"su"}},
        {"sudooo", {"sudo"}},
        {"odus", {"sudo"}},
        {"groupsss", {"groups"}},
        {"spuorg", {"groups"}},
        {"idd", {"id"}},
        {"di", {"id"}},
        {"lognamee", {"logname"}},
        {"emangogl", {"logname"}},
        {"whoamiiii", {"whoami"}},
        {"imaohw", {"whoami"}},
        {"userss", {"users"}},
        {"sresu", {"users"}},
        {"whoo", {"who"}},
        {"ohw", {"who"}},
        {"ww", {"w"}},
        {"pinkyyyy", {"pinky"}},
        {"yknip", {"pinky"}},
        {"fingerrrr", {"finger"}},
        {"regnif", {"finger"}},
        {"lastt", {"last"}},
        {"tsal", {"last"}},
        {"lastbb", {"lastb"}},
        {"btsall", {"lastb"}},
        {"lastloggg", {"lastlog"}},
        {"goltsal", {"lastlog"}},
        {"melddd", {"mesg"}},
        {"gsem", {"mesg"}},
        {"writee", {"write"}},
        {"etirw", {"write"}},
        {"wallll", {"wall"}},
        {"llaw", {"wall"}},
        {"talkkkk", {"talk"}},
        {"klat", {"talk"}},
        {"ytalkkkk", {"ytalk"}},
        {"klatx", {"ytalk"}},
        {"uptimeee", {"uptime"}},
        {"emitpu", {"uptime"}},
        {"ww", {"w"}},
        {"vmlstat", {"vmstat"}},
        {"tatsml", {"vmstat"}},
        {"iostattt", {"iostat"}},
        {"tatsi", {"iostat"}},
        {"sarrrr", {"sar"}},
        {"ras", {"sar"}},
        {"toppp", {"top"}},
        {"potp", {"top"}},
        {"htoppp", {"htop"}},
        {"potho", {"htop"}},
        {"atoppp", {"atop"}},
        {"pota", {"atop"}},
        {"itoppp", {"iotop"}},
        {"poti", {"iotop"}},
        {"powertoppp", {"powertop"}},
        {"potrewo", {"powertop"}},
        {"nmonnn", {"nmon"}},
        {"nomn", {"nmon"}},
        {"sysmonfff", {"sysmon"}},
        {"nomsys", {"sysmon"}},
        {"dstattt", {"dstat"}},
        {"tatsd", {"dstat"}},
        {"ifstattt", {"ifstat"}},
        {"tatsfi", {"ifstat"}},
        {"netstattt", {"netstat"}},
        {"tatsten", {"netstat"}},
        {"ssss", {"ss"}},
        {"s", {"ss"}},
        {"lsofff", {"lsof"}},
        {"fosl", {"lsof"}},
        {"fuser", {"fuser"}},
        {"resuf", {"fuser"}},
        {"pidofff", {"pidof"}},
        {"fodip", {"pidof"}},
        {"pgrepppp", {"pgrep"}},
        {"pergp", {"pgrep"}},
        {"pkillll", {"pkill"}},
        {"llikp", {"pkill"}},
        {"killallll", {"killall"}},
        {"llalik", {"killall"}},
        {"killlll", {"kill"}},
        {"llik", {"kill"}},
        {"jobsss", {"jobs"}},
        {"sboj", {"jobs"}},
        {"bggg", {"bg"}},
        {"gb", {"bg"}},
        {"fggg", {"fg"}},
        {"gf", {"fg"}},
        {"nohuppp", {"nohup"}},
        {"puhon", {"nohup"}},
        {"discownnn", {"disown"}},
        {"nwocsd", {"disown"}},
        {"attt", {"at"}},
        {"ta", {"at"}},
        {"atqqq", {"atq"}},
        {"qta", {"atq"}},
        {"atrmm", {"atrm"}},
        {"mrta", {"atrm"}},
        {"batchhh", {"batch"}},
        {"hctab", {"batch"}},
        {"crontabbb", {"crontab"}},
        {"batnoc", {"crontab"}},
        {"anacronnn", {"anacron"}},
        {"norcana", {"anacron"}},
        {"mounnt", {"mount"}},
        {"tnuom", {"mount"}},
        {"umounnt", {"umount"}},
        {"tnuomu", {"umount"}},
        {"dfff", {"df"}},
        {"fd", {"df"}},
        {"duuu", {"du"}},
        {"ud", {"du"}},
        {"lsblkkkk", {"lsblk"}},
        {"klbsl", {"lsblk"}},
        {"blkiddd", {"blkid"}},
        {"dikbl", {"blkid"}},
        {"lscpuuu", {"lscpu"}},
        {"upcsl", {"lscpu"}},
        {"lsmemm", {"lsmem"}},
        {"memsl", {"lsmem"}},
        {"lshwww", {"lshw"}},
        {"whsl", {"lshw"}},
        {"lspciii", {"lspci"}},
        {"icpsl", {"lspci"}},
        {"lsusbbb", {"lsusb"}},
        {"bsusl", {"lsusb"}},
        {"dmesggg", {"dmesg"}},
        {"gsemd", {"dmesg"}},
        {"unamee", {"uname"}},
        {"emanu", {"uname"}},
        {"hostnamee", {"hostname"}},
        {"emantsoh", {"hostname"}},
        {"domanee", {"domainname"}},
        {"emannod", {"domainname"}},
        {"nisdomainnamee", {"nisdomainname"}},
        {"emnanniamsod", {"nisdomainname"}},
        {"ypdomainnamee", {"ypdomainname"}},
        {"emannidpoy", {"ypdomainname"}},
        {"ifconfiggg", {"ifconfig"}},
        {"gfiocfi", {"ifconfig"}},
        {"ippp", {"ip"}},
        {"pi", {"ip"}},
        {"iwconfiggg", {"iwconfig"}},
        {"gfiocwi", {"iwconfig"}},
        {"iwlisttt", {"iwlist"}},
        {"tsilwi", {"iwlist"}},
        {"iwgetiddd", {"iwgetid"}},
        {"ditegwi", {"iwgetid"}},
        {"iwpriv", {"iwpriv"}},
        {"virpwi", {"iwpriv"}},
        {"iwspyyy", {"iwspy"}},
        {"yspwi", {"iwspy"}},
        {"routeee", {"route"}},
        {"etuor", {"route"}},
        {"pinggg", {"ping"}},
        {"gnip", {"ping"}},
        {"ping6666", {"ping6"}},
        {"6gnip", {"ping6"}},
        {"tracerouteee", {"traceroute"}},
        {"etuoreca", {"traceroute"}},
        {"tracepathhhh", {"tracepath"}},
        {"htapecar", {"tracepath"}},
        {"mtrrrr", {"mtr"}},
        {"rtm", {"mtr"}},
        {"diggg", {"dig"}},
        {"gid", {"dig"}},
        {"nslookuppp", {"nslookup"}},
        {"pukoolsn", {"nslookup"}},
        {"hosttt", {"host"}},
        {"tsoh", {"host"}},
        {"whoisss", {"whois"}},
        {"siohw", {"whois"}},
        {"curlll", {"curl"}},
        {"lruc", {"curl"}},
        {"wgettt", {"wget"}},
        {"tegw", {"wget"}},
        {"lynxxx", {"lynx"}},
        {"xnyl", {"lynx"}},
        {"w3mmm", {"w3m"}},
        {"m3w", {"w3m"}},
        {"linksss", {"links"}},
        {"sknil", {"links"}},
        {"elinksss", {"elinks"}},
        {"sknile", {"elinks"}},
        {"ftppp", {"ftp"}},
        {"ptf", {"ftp"}},
        {"sftppp", {"sftp"}},
        {"ptfs", {"sftp"}},
        {"ncftppp", {"ncftp"}},
        {"ptfcn", {"ncftp"}},
        {"lftp", {"lftp"}},
        {"ptfl", {"lftp"}},
        {"rsyncc", {"rsync"}},
        {"cnysr", {"rsync"}},
        {"scppp", {"scp"}},
        {"pcs", {"scp"}},
        {"sshhhh", {"ssh"}},
        {"hss", {"ssh"}},
        {"ssh-keygennnn", {"ssh-keygen"}},
        {"negeyk-hss", {"ssh-keygen"}},
        {"ssh-copyidddd", {"ssh-copy-id"}},
        {"di-ypoc-hss", {"ssh-copy-id"}},
        {"ssh-addddd", {"ssh-add"}},
        {"dda-hss", {"ssh-add"}},
        {"ssh-agenttt", {"ssh-agent"}},
        {"tnega-hss", {"ssh-agent"}},
        {"telnett", {"telnet"}},
        {"tenlet", {"telnet"}},
        {"rloginn", {"rlogin"}},
        {"nigolr", {"rlogin"}},
        {"rshhhh", {"rsh"}},
        {"hsr", {"rsh"}},
        {"rcppp", {"rcp"}},
        {"pcr", {"rcp"}},
        {"finger", {"finger"}},
        {"regnif", {"finger"}},
        {"rwho", {"rwho"}},
        {"ohwr", {"rwho"}},
        {"ruptimeee", {"ruptime"}},
        {"emitpur", {"ruptime"}},
        {"talkk", {"talk"}},
        {"klat", {"talk"}},
        {"writee", {"write"}},
        {"etirw", {"write"}},
        {"mesggg", {"mesg"}},
        {"gsem", {"mesg"}},
        {"wallll", {"wall"}},
        {"llaw", {"wall"}},
        {"mailll", {"mail"}},
        {"liam", {"mail"}},
        {"sendmailll", {"sendmail"}},
        {"liamdnes", {"sendmail"}},
        {"muutt", {"mutt"}},
        {"ttum", {"mutt"}},
        {"pinee", {"pine"}},
        {"enip", {"pine"}},
        {"alpinee", {"alpine"}},
        {"enipla", {"alpine"}},
        {"elmm", {"elm"}},
        {"mle", {"elm"}},
        {"maixxxx", {"mail"}},
        {"xiamm", {"mail"}},
        {"procmailll", {"procmail"}},
        {"liamc", {"procmail"}},
        {"formail", {"formail"}},
        {"liamrof", {"formail"}},
        {"vacation", {"vacation"}},
        {"noiitacav", {"vacation"}},
        {"biffff", {"biff"}},
        {"ffib", {"biff"}},
        {"froomm", {"from"}},
        {"morf", {"from"}},
        {"newaliasesss", {"newaliases"}},
        {"sesailawen", {"newaliases"}},
        {"vttt", {"vt"}},
        {"tv", {"vt"}},
        {"viiii", {"vi"}},
        {"iv", {"vi"}},
        {"vimmm", {"vim"}},
        {"miv", {"vim"}},
        {"emacssss", {"emacs"}},
        {"scame", {"emacs"}},
        {"nanoo", {"nano"}},
        {"onan", {"nano"}},
        {"picoo", {"pico"}},
        {"ocip", {"pico"}},
        {"joe", {"joe"}},
        {"eoj", {"joe"}},
        {"jeddd", {"jed"}},
        {"dej", {"jed"}},
        {"mccccc", {"mc"}},
        {"cm", {"mc"}},
        {"lesss", {"less"}},
        {"ssel", {"less"}},
        {"moree", {"more"}},
        {"erom", {"more"}},
        {"pggg", {"pg"}},
        {"gp", {"pg"}},
        {"lnnn", {"ln"}},
        {"nl", {"ln"}},
        {"linkk", {"link"}},
        {"knil", {"link"}},
        {"unlinkk", {"unlink"}},
        {"knilnu", {"unlink"}},
        {"copyyy", {"cp"}},
        {"yp", {"cp"}},
        {"movee", {"mv"}},
        {"evom", {"mv"}},
        {"rmmm", {"rm"}},
        {"mr", {"rm"}},
        {"rmdirrr", {"rmdir"}},
        {"ridmr", {"rmdir"}},
        {"mkdirr", {"mkdir"}},
        {"ridkm", {"mkdir"}},
        {"chmoddd", {"chmod"}},
        {"domhc", {"chmod"}},
        {"chownn", {"chown"}},
        {"nwohc", {"chown"}},
        {"chgrppp", {"chgrp"}},
        {"prgc", {"chgrp"}},
        {"umaskk", {"umask"}},
        {"ksamu", {"umask"}},
        {"touchhh", {"touch"}},
        {"hcuot", {"touch"}},
        {"stattt", {"stat"}},
        {"tats", {"stat"}},
        {"fileee", {"file"}},
        {"elif", {"file"}},
        {"typeee", {"type"}},
        {"epyt", {"type"}},
        {"whichhhh", {"which"}},
        {"hcihw", {"which"}},
        {"whereisss", {"whereis"}},
        {"sierehw", {"whereis"}},
        {"locateee", {"locate"}},
        {"etacol", {"locate"}},
        {"updatedbbb", {"updatedb"}},
        {"bdetadpu", {"updatedb"}},
        {"findddd", {"find"}},
        {"dnif", {"find"}},
        {"xargsss", {"xargs"}},
        {"sgrax", {"xargs"}},
        {"grepppp", {"grep"}},
        {"perggg", {"grep"}},
        {"egreppp", {"egrep"}},
        {"pergee", {"egrep"}},
        {"fgreppp", {"fgrep"}},
        {"pergff", {"fgrep"}},
        {"rgreppp", {"rgrep"}},
        {"pergr", {"rgrep"}},
        {"zipgreppp", {"zipgrep"}},
        {"pergpiz", {"zipgrep"}},
        {"bzgreppp", {"bzgrep"}},
        {"pergzb", {"bzgrep"}},
        {"lzgreppp", {"lzgrep"}},
        {"pergzl", {"lzgrep"}},
        {"xzgreppp", {"xzgrep"}},
        {"pergzx", {"xzgrep"}},
        {"zgrepp", {"zgrep"}},
        {"pergz", {"zgrep"}},
        {"cattt", {"cat"}},
        {"tac", {"tac"}},
        {"morr", {"more"}},
        {"rom", {"more"}},
        {"lessee", {"less"}},
        {"ssel", {"less"}},
        {"headdd", {"head"}},
        {"daeh", {"head"}},
        {"tailll", {"tail"}},
        {"liat", {"tail"}},
        {"revvv", {"rev"}},
        {"ver", {"rev"}},
        {"wcccc", {"wc"}},
        {"cw", {"wc"}},
        {"sorttt", {"sort"}},
        {"tros", {"sort"}},
        {"uniqq", {"uniq"}},
        {"qinu", {"uniq"}},
        {"commm", {"comm"}},
        {"moc", {"comm"}},
        {"joinn", {"join"}},
        {"nioj", {"join"}},
        {"pastee", {"paste"}},
        {"etsap", {"paste"}},
        {"cutt", {"cut"}},
        {"tuc", {"cut"}},
        {"trrr", {"tr"}},
        {"rt", {"tr"}},
        {"sedd", {"sed"}},
        {"des", {"sed"}},
        {"awkk", {"awk"}},
        {"kwa", {"awk"}},
        {"diffff", {"diff"}},
        {"ffid", {"diff"}},
        {"diff3333", {"diff3"}},
        {"3ffid", {"diff3"}},
        {"sdifff", {"sdiff"}},
        {"ffids", {"sdiff"}},
        {"cmpp", {"cmp"}},
        {"pmc", {"cmp"}},
        {"expandd", {"expand"}},
        {"dnapxe", {"expand"}},
        {"unexpandd", {"unexpand"}},
        {"dnapxenu", {"unexpand"}},
        {"folddd", {"fold"}},
        {"dlof", {"fold"}},
        {"fmttt", {"fmt"}},
        {"tmf", {"fmt"}},
        {"prr", {"pr"}},
        {"rp", {"pr"}},
        {"nll", {"nl"}},
        {"ln", {"nl"}},
        {"spliitt", {"split"}},
        {"tilps", {"split"}},
        {"csplitt", {"csplit"}},
        {"tilpsc", {"csplit"}},
        {"ptxxx", {"ptx"}},
        {"xtp", {"ptx"}},
        {"ood", {"od"}},
        {"do", {"od"}},
        {"hexdumppp", {"hexdump"}},
        {"pmudxeh", {"hexdump"}},
        {"xxddd", {"xxd"}},
        {"dxx", {"xxd"}},
        {"stringsss", {"strings"}},
        {"sgnirts", {"strings"}},
        {"objdumppp", {"objdump"}},
        {"pmudbjo", {"objdump"}},
        {"nmm", {"nm"}},
        {"mn", {"nm"}},
        {"sizee", {"size"}},
        {"ezis", {"size"}},
        {"strippp", {"strip"}},
        {"pirts", {"strip"}},
        {"arrr", {"ar"}},
        {"ra", {"ar"}},
        {"ranlibb", {"ranlib"}},
        {"bilnar", {"ranlib"}},
        {"ldd", {"ldd"}},
        {"ddl", {"ldd"}},
        {"ldconfiggg", {"ldconfig"}},
        {"gifocl", {"ldconfig"}},
        {"makee", {"make"}},
        {"ekam", {"make"}},
        {"cmakee", {"cmake"}},
        {"ekam", {"cmake"}},
        {"autoconfff", {"autoconf"}},
        {"fnocotua", {"autoconf"}},
        {"automakee", {"automake"}},
        {"ekamotua", {"automake"}},
        {"configuree", {"configure"}},
        {"erugifnoc", {"configure"}},
        {"installll", {"install"}},
        {"llatsni", {"install"}},
        {"gcccc", {"gcc"}},
        {"cgc", {"gcc"}},
        {"g++", {"g++"}},
        {"++g", {"g++"}},
        {"clanggg", {"clang"}},
        {"gnalc", {"clang"}},
        {"clang++", {"clang++"}},
        {"++gnalc", {"clang++"}},
        {"javaccc", {"javac"}},
        {"cavaj", {"javac"}},
        {"javaaa", {"java"}},
        {"avaj", {"java"}},
        {"pythonnn", {"python"}},
        {"nohtyp", {"python"}},
        {"python3333", {"python3"}},
        {"3nohtyp", {"python3"}},
        {"pippp", {"pip"}},
        {"pip", {"pip"}},
        {"pip3333", {"pip3"}},
        {"3pip", {"pip3"}},
        {"nodee", {"node"}},
        {"edon", {"node"}},
        {"npmm", {"npm"}},
        {"mpn", {"npm"}},
        {"yarnnn", {"yarn"}},
        {"nray", {"yarn"}},
        {"rubyyyy", {"ruby"}},
        {"ybur", {"ruby"}},
        {"gemm", {"gem"}},
        {"meg", {"gem"}},
        {"bundlerr", {"bundler"}},
        {"reldnub", {"bundler"}},
        {"rakee", {"rake"}},
        {"ekar", {"rake"}},
        {"railsss", {"rails"}},
        {"sliar", {"rails"}},
        {"perlll", {"perl"}},
        {"lrep", {"perl"}},
        {"cpannn", {"cpan"}},
        {"napc", {"cpan"}},
        {"phppp", {"php"}},
        {"php", {"php"}},
        {"composerr", {"composer"}},
        {"resopmo", {"composer"}},
        {"rustccc", {"rustc"}},
        {"ctsur", {"rustc"}},
        {"cargoo", {"cargo"}},
        {"ograc", {"cargo"}},
        {"gooo", {"go"}},
        {"og", {"go"}},
        {"swifttt", {"swift"}},
        {"tfiws", {"swift"}},
        {"kotlinnn", {"kotlin"}},
        {"niltok", {"kotlin"}},
        {"scalaaaa", {"scala"}},
        {"alacs", {"scala"}},
        {"sbttt", {"sbt"}},
        {"tbs", {"sbt"}},
        {"gradleee", {"gradle"}},
        {"eldarg", {"gradle"}},
        {"mavennn", {"maven"}},
        {"nevam", {"maven"}},
        {"anttt", {"ant"}},
        {"tna", {"ant"}},
        {"dockerr", {"docker"}},
        {"rekcod", {"docker"}},
        {"docker-composee", {"docker-compose"}},
        {"esopmc-rekcod", {"docker-compose"}},
        {"kubectlll", {"kubectl"}},
        {"ltcebu", {"kubectl"}},
        {"helmm", {"helm"}},
        {"mleh", {"helm"}},
        {"terraformm", {"terraform"}},
        {"mrofarr", {"terraform"}},
        {"ansibleee", {"ansible"}},
        {"elbisna", {"ansible"}},
        {"vagranttt", {"vagrant"}},
        {"tnargav", {"vagrant"}},
        {"gitt", {"git"}},
        {"tig", {"git"}},
        {"svnnn", {"svn"}},
        {"nvs", {"svn"}},
        {"hggg", {"hg"}},
        {"gh", {"hg"}},
        {"bzrr", {"bzr"}},
        {"rzb", {"bzr"}},
        {"cvsss", {"cvs"}},
        {"svc", {"cvs"}},
        {"rcsss", {"rcs"}},
        {"scr", {"rcs"}},
        {"tarr", {"tar"}},
        {"rat", {"tar"}},
        {"gzippp", {"gzip"}},
        {"pizg", {"gzip"}},
        {"gunzippp", {"gunzip"}},
        {"piznung", {"gunzip"}},
        {"zcattt", {"zcat"}},
        {"tacaz", {"zcat"}},
        {"bzip2222", {"bzip2"}},
        {"2pizb", {"bzip2"}},
        {"bunzip2222", {"bunzip2"}},
        {"2piznu", {"bunzip2"}},
        {"bzcat", {"bzcat"}},
        {"tacb", {"bzcat"}},
        {"xzzzz", {"xz"}},
        {"zx", {"xz"}},
        {"unxzzz", {"unxz"}},
        {"zxnu", {"unxz"}},
        {"xzcattt", {"xzcat"}},
        {"tacx", {"xzcat"}},
        {"lzmaaa", {"lzma"}},
        {"amzl", {"lzma"}},
        {"unlzmaaaa", {"unlzma"}},
        {"amzlnu", {"unlzma"}},
        {"lzcattt", {"lzcat"}},
        {"tacl", {"lzcat"}},
        {"zippp", {"zip"}},
        {"piz", {"zip"}},
        {"unzippp", {"unzip"}},
        {"piznu", {"unzip"}},
        {"7zzzz", {"7z"}},
        {"z7", {"7z"}},
        {"rarr", {"rar"}},
        {"rar", {"rar"}},
        {"unrarr", {"unrar"}},
        {"rarnu", {"unrar"}},
        {"cabextracttt", {"cabextract"}},
        {"tcartxebac", {"cabextract"}},
        {"arjj", {"arj"}},
        {"jra", {"arj"}},
        {"lhaaaa", {"lha"}},
        {"ahl", {"lha"}},
        {"lzoppp", {"lzop"}},
        {"pozl", {"lzop"}},
        {"unlzoppp", {"unlzop"}},
        {"pozlnu", {"unlzop"}},
        {"compressss", {"compress"}},
        {"sserpmoc", {"compress"}},
        {"uncompressss", {"uncompress"}},
        {"sserpmocnu", {"uncompress"}},
        {"zcatttt", {"zcat"}},
        {"tacss", {"zcat"}},
        {"packk", {"pack"}},
        {"kcap", {"pack"}},
        {"unpackk", {"unpack"}},
        {"kcapnu", {"unpack"}},
        {"pcattt", {"pcat"}},
        {"tacp", {"pcat"}},
        {"squashfsss", {"squashfs"}},
        {"sfhsaus", {"squashfs"}},
        {"mksquashfsss", {"mksquashfs"}},
        {"sfhsauqskm", {"mksquashfs"}},
        {"unsquashfsss", {"unsquashfs"}},
        {"sfhsauqsnu", {"unsquashfs"}},
        {"cramfsss", {"cramfs"}},
        {"sfmarc", {"cramfs"}},
        {"mkcramfsss", {"mkcramfs"}},
        {"sfmarckm", {"mkcramfs"}},
        {"isosizeee", {"isosize"}},
        {"ezisosi", {"isosize"}},
        {"mkisofsss", {"mkisofs"}},
        {"sfosikm", {"mkisofs"}},
        {"genisoimage", {"genisoimage"}},
        {"egamiosi", {"genisoimage"}},
        {"isolll", {"iso"}},
        {"osi", {"iso"}},
        {"cdrecorddd", {"cdrecord"}},
        {"drocerc", {"cdrecord"}},
        {"wodimnnn", {"wodim"}},
        {"midow", {"wodim"}},
        {"cdrddaaooo", {"cdrdao"}},
        {"oadrdc", {"cdrdao"}},
        {"readcddd", {"readcd"}},
        {"dcda", {"readcd"}},
        {"cd-infooo", {"cd-info"}},
        {"ofni-dc", {"cd-info"}},
        {"cd-driveee", {"cd-drive"}},
        {"evird-dc", {"cd-drive"}},
        {"cd-readd", {"cd-read"}},
        {"daer-dc", {"cd-read"}},
        {"cdparanoia", {"cdparanoia"}},
        {"aionapa", {"cdparanoia"}},
        {"cuebreatk", {"cuebreakpoints"}},
        {"stniopka", {"cuebreakpoints"}},
        {"cue2toc", {"cue2toc"}},
        {"cot2euc", {"cue2toc"}},
        {"toc2cue", {"toc2cue"}},
        {"euc2cot", {"toc2cue"}},
        {"eject", {"eject"}},
        {"tceje", {"eject"}},
        {"mountt", {"mount"}},
        {"tnuom", {"mount"}},
        {"umountt", {"umount"}},
        {"tnuomu", {"umount"}},
        {"losetuppp", {"losetup"}},
        {"putesol", {"losetup"}},
        {"dfff", {"df"}},
        {"fd", {"df"}},
        {"duuu", {"du"}},
        {"ud", {"du"}},
        {"quotaaa", {"quota"}},
        {"atouq", {"quota"}},
        {"quotacheckk", {"quotacheck"}},
        {"kcehcatou", {"quotacheck"}},
        {"quotaonnnn", {"quotaon"}},
        {"noa", {"quotaon"}},
        {"quotaofff", {"quotaoff"}},
        {"ffoa", {"quotaoff"}},
        {"editquotaaa", {"edquota"}},
        {"atouqtide", {"edquota"}},
        {"repquotaaa", {"repquota"}},
        {"atouqper", {"repquota"}},
        {"quotastatsss", {"quotastats"}},
        {"statsa", {"quotastats"}},
        {"warnquotaaa", {"warnquota"}},
        {"atouqnra", {"warnquota"}},
        {"fsckkk", {"fsck"}},
        {"kcsf", {"fsck"}},
        {"fsck.ext2222", {"fsck.ext2"}},
        {"2txe.kcsf", {"fsck.ext2"}},
        {"fsck.ext3333", {"fsck.ext3"}},
        {"3txe.kcsf", {"fsck.ext3"}},
        {"fsck.ext4444", {"fsck.ext4"}},
        {"4txe.kcsf", {"fsck.ext4"}},
        {"fsck.reiserfsss", {"fsck.reiserfs"}},
        {"sfresier.kcsf", {"fsck.reiserfs"}},
        {"fsck.xfsss", {"fsck.xfs"}},
        {"sfx.kcsf", {"fsck.xfs"}},
        {"fsck.jfsss", {"fsck.jfs"}},
        {"sfj.kcsf", {"fsck.jfs"}},
        {"fsck.vfattt", {"fsck.vfat"}},
        {"tafv.kcsf", {"fsck.vfat"}},
        {"fsck.ntfsss", {"fsck.ntfs"}},
        {"sftn.kcsf", {"fsck.ntfs"}},
        {"mkfs", {"mkfs"}},
        {"sfkm", {"mkfs"}},
        {"mkfs.ext2222", {"mkfs.ext2"}},
        {"2txe.sfkm", {"mkfs.ext2"}},
        {"mkfs.ext3333", {"mkfs.ext3"}},
        {"3txe.sfkm", {"mkfs.ext3"}},
        {"mkfs.ext4444", {"mkfs.ext4"}},
        {"4txe.sfkm", {"mkfs.ext4"}},
        {"mkfs.reiserfsss", {"mkfs.reiserfs"}},
        {"sfresier.sfkm", {"mkfs.reiserfs"}},
        {"mkfs.xfsss", {"mkfs.xfs"}},
        {"sfx.sfkm", {"mkfs.xfs"}},
        {"mkfs.jfsss", {"mkfs.jfs"}},
        {"sfj.sfkm", {"mkfs.jfs"}},
        {"mkfs.vfattt", {"mkfs.vfat"}},
        {"tafv.sfkm", {"mkfs.vfat"}},
        {"mkfs.ntfsss", {"mkfs.ntfs"}},
        {"sftn.sfkm", {"mkfs.ntfs"}},
        {"tunefsss", {"tunefs"}},
        {"sfenu", {"tunefs"}},
        {"tune2fsss", {"tune2fs"}},
        {"sf2enu", {"tune2fs"}},
        {"dumpe2fsss", {"dumpe2fs"}},
        {"sf2epmu", {"dumpe2fs"}},
        {"debugfsss", {"debugfs"}},
        {"sfgubed", {"debugfs"}},
        {"badblockssss", {"badblocks"}},
        {"skcoldab", {"badblocks"}},
        {"e2fsck", {"e2fsck"}},
        {"kcf2e", {"e2fsck"}},
        {"e2labelll", {"e2label"}},
        {"leba2e", {"e2label"}},
        {"resize2fsss", {"resize2fs"}},
        {"sf2eziser", {"resize2fs"}},
        {"mke2fsss", {"mke2fs"}},
        {"sf2ekm", {"mke2fs"}},
        {"hdparmm", {"hdparm"}},
        {"mpradh", {"hdparm"}},
        {"fdiskk", {"fdisk"}},
        {"ksidf", {"fdisk"}},
        {"cfdiskk", {"cfdisk"}},
        {"ksidfc", {"cfdisk"}},
        {"sfdiskk", {"sfdisk"}},
        {"ksids", {"sfdisk"}},
        {"parteddd", {"parted"}},
        {"detrap", {"parted"}},
        {"gparteddd", {"gparted"}},
        {"detrapg", {"gparted"}},
        {"partprobeee", {"partprobe"}},
        {"eborptrap", {"partprobe"}},
        {"lsblikk", {"lsblk"}},
        {"klbsl", {"lsblk"}},
        {"blkidddd", {"blkid"}},
        {"dikl", {"blkid"}},
        {"lsmoddd", {"lsmod"}},
        {"domsl", {"lsmod"}},
        {"insmoddd", {"insmod"}},
        {"domsni", {"insmod"}},
        {"rmmoddd", {"rmmod"}},
        {"domm", {"rmmod"}},
        {"modprobeee", {"modprobe"}},
        {"eborpdom", {"modprobe"}},
        {"modinfoooo", {"modinfo"}},
        {"ofnidom", {"modinfo"}},
        {"depmoddd", {"depmod"}},
        {"dompde", {"depmod"}},
        {"dmesggg", {"dmesg"}},
        {"gsemd", {"dmesg"}},
        {"journalctlll", {"journalctl"}},
        {"ltcanr", {"journalctl"}},
        {"systemctlll", {"systemctl"}},
        {"ltcmets", {"systemctl"}},
        {"servicee", {"service"}},
        {"ecivres", {"service"}},
        {"chkconfiggg", {"chkconfig"}},
        {"gfiock", {"chkconfig"}},
        {"updatercdd", {"update-rc.d"}},
        {"d.cr-etadp", {"update-rc.d"}},
        {"initctlll", {"initctl"}},
        {"ltctini", {"initctl"}},
        {"startt", {"start"}},
        {"trats", {"start"}},
        {"stoppp", {"stop"}},
        {"pots", {"stop"}},
        {"restarttt", {"restart"}},
        {"tratser", {"restart"}},
        {"reloadd", {"reload"}},
        {"daole", {"reload"}},
        {"statusss", {"status"}},
        {"sutats", {"status"}},
        {"enableee", {"enable"}},
        {"elbane", {"enable"}},
        {"disableee", {"disable"}},
        {"elbasid", {"disable"}},
        {"maskk", {"mask"}},
        {"ksam", {"mask"}},
        {"unmaskk", {"unmask"}},
        {"ksam", {"unmask"}},
        {"daemontoolsss", {"daemontools"}},
        {"slootno", {"daemontools"}},
        {"supervisord", {"supervisord"}},
        {"drosivr", {"supervisord"}},
        {"supervisorctlll", {"supervisorctl"}},
        {"ltcsivrepus", {"supervisorctl"}},
        {"runsvv", {"runsv"}},
        {"vsnur", {"runsv"}},
        {"svv", {"sv"}},
        {"vs", {"sv"}},
        {"uname", {"uname"}},
        {"emanu", {"uname"}},
        {"lscpuuu", {"lscpu"}},
        {"upcsl", {"lscpu"}},
        {"lsmemm", {"lsmem"}},
        {"memsll", {"lsmem"}},
        {"lshwww", {"lshw"}},
        {"whsl", {"lshw"}},
        {"lspciii", {"lspci"}},
        {"icpsl", {"lspci"}},
        {"lsusbbb", {"lsusb"}},
        {"bsusl", {"lsusb"}},
        {"dmidecodeee", {"dmidecode"}},
        {"edoced", {"dmidecode"}},
        {"hwinfoooo", {"hwinfo"}},
        {"ofniwh", {"hwinfo"}},
        {"lspccarddd", {"lspcmcia"}},
        {"aircmcpsl", {"lspcmcia"}},
        {"setpciii", {"setpci"}},
        {"icpte", {"setpci"}},
        {"lsattrrr", {"lsattr"}},
        {"rttas", {"lsattr"}},
        {"chattrr", {"chattr"}},
        {"rtahc", {"chattr"}},
        {"aclll", {"acl"}},
        {"lca", {"acl"}},
        {"getfaclll", {"getfacl"}},
        {"lcafeg", {"getfacl"}},
        {"setfaclll", {"setfacl"}},
        {"lcafest", {"setfacl"}},
        {"selinuxxx", {"selinux"}},
        {"xunil", {"selinux"}},
        {"sestatusss", {"sestatus"}},
        {"sutates", {"sestatus"}},
        {"getenforceee", {"getenforce"}},
        {"ecrofneteg", {"getenforce"}},
        {"setenforceee", {"setenforce"}},
        {"ecrofnetes", {"setenforce"}},
        {"setseboolll", {"setsebool"}},
        {"loobeses", {"setsebool"}},
        {"getseboolll", {"getsebool"}},
        {"loobeses", {"getsebool"}},
        {"semanageee", {"semanage"}},
        {"eganames", {"semanage"}},
        {"restoreconnn", {"restorecon"}},
        {"noceroser", {"restorecon"}},
        {"chcconnn", {"chcon"}},
        {"nochc", {"chcon"}},
        {"runconnn", {"runcon"}},
        {"nocnur", {"runcon"}},
        {"auditctlll", {"auditctl"}},
        {"ltctidua", {"auditctl"}},
        {"auditdd", {"auditd"}},
        {"dtidua", {"auditd"}},
        {"ausearchhh", {"ausearch"}},
        {"hcraesua", {"ausearch"}},
        {"aureporttt", {"aureport"}},
        {"troperua", {"aureport"}},
        {"iptablesss", {"iptables"}},
        {"selbat", {"iptables"}},
        {"ip6tablesss", {"ip6tables"}},
        {"selbat6", {"ip6tables"}},
        {"iptables-saveee", {"iptables-save"}},
        {"evas-sle", {"iptables-save"}},
        {"iptables-restoree", {"iptables-restore"}},
        {"eroser-sel", {"iptables-restore"}},
        {"nftablesss", {"nftables"}},
        {"selbatfn", {"nftables"}},
        {"nfttt", {"nft"}},
        {"tfn", {"nft"}},
        {"ufwww", {"ufw"}},
        {"wfu", {"ufw"}},
        {"firewalldd", {"firewalld"}},
        {"dllaweri", {"firewalld"}},
        {"firewall-cmdd", {"firewall-cmd"}},
        {"dmc-llaweri", {"firewall-cmd"}},
        {"crontabbb", {"crontab"}},
        {"batnor", {"crontab"}},
        {"cronnn", {"cron"}},
        {"norc", {"cron"}},
        {"anacronnn", {"anacron"}},
        {"norcana", {"anacron"}},
        {"attt", {"at"}},
        {"ta", {"at"}},
        {"atqqq", {"atq"}},
        {"qta", {"atq"}},
        {"atrmm", {"atrm"}},
        {"mrat", {"atrm"}},
        {"batchhh", {"batch"}},
        {"hctab", {"batch"}},
        {"logrotateee", {"logrotate"}},
        {"etatorgo", {"logrotate"}},
        {"logwatchhh", {"logwatch"}},
        {"hctawgol", {"logwatch"}},
        {"rsyslogg", {"rsyslog"}},
        {"golsy", {"rsyslog"}},
        {"rsyslogdd", {"rsyslogd"}},
        {"dgolsyr", {"rsyslogd"}},
        {"sysloggg", {"syslog"}},
        {"golsys", {"syslog"}},
        {"syslog-nggg", {"syslog-ng"}},
        {"gn-golsys", {"syslog-ng"}},
        {"loggerr", {"logger"}},
        {"reggol", {"logger"}},
        {"tailff", {"tailf"}},
        {"fliat", {"tailf"}},
        {"multitailll", {"multitail"}},
        {"liatitlum", {"multitail"}},
        {"lessss", {"less"}},
        {"ssel", {"less"}},
        {"zlessss", {"zless"}},
        {"sselz", {"zless"}},
        {"bzlessss", {"bzless"}},
        {"sselzb", {"bzless"}},
        {"xzlessss", {"xzless"}},
        {"sselzx", {"xzless"}},
        {"lzlessss", {"lzless"}},
        {"sselzl", {"lzless"}},
        {"lesseeechoooo", {"lessecho"}},
        {"ohcesse", {"lessecho"}},
        {"lesskeyyyy", {"lesskey"}},
        {"yekssel", {"lesskey"}},
        {"lessfileeee", {"lessfile"}},
        {"elifssel", {"lessfile"}},
        {"lessppipe", {"lesspipe"}},
        {"epipssel", {"lesspipe"}},
    };
    
    auto it = common_typos.find(command);
    if (it != common_typos.end()) {
        for (const auto& suggestion : it->second) {
            suggestions.push_back("Did you mean: " + suggestion);
        }
        return suggestions;
    }
    
    // Check for common patterns and suggest alternatives
    if (command.length() >= 2) {
        // Check if it's a close match to common commands
        std::vector<std::string> common_commands = {
            "ls", "cd", "pwd", "cat", "echo", "grep", "find", "which", "man",
            "cp", "mv", "rm", "mkdir", "rmdir", "chmod", "chown", "chgrp",
            "tar", "gzip", "gunzip", "zip", "unzip", "wget", "curl", "ssh",
            "scp", "rsync", "ping", "netstat", "ps", "top", "kill", "killall",
            "df", "du", "mount", "umount", "fdisk", "free", "history", "alias",
            "export", "source", "bash", "zsh", "vim", "nano", "emacs", "git",
            "make", "gcc", "python", "python3", "node", "npm", "docker"
        };
        
        for (const auto& cmd : common_commands) {
            int distance = edit_distance(command, cmd);
            if (distance <= 2 && distance > 0) {
                suggestions.push_back("Did you mean '" + cmd + "'?");
            }
        }
    }
    
    // Check PATH for similar commands
    const char* path = getenv("PATH");
    if (path && suggestions.empty()) {
        suggestions.push_back("Command not found. Try 'which " + command + "' to check if it's installed.");
        suggestions.push_back("You might need to install a package or check your PATH.");
    }
    
    // Limit suggestions
    if (suggestions.size() > 3) {
        suggestions.resize(3);
    }
    
    return suggestions;
}

std::vector<std::string> generate_cd_suggestions(const std::string& target_dir, 
                                                const std::string& current_dir) {
    std::vector<std::string> suggestions;
    
    // Find similar directory names in current directory
    std::vector<std::string> similar = find_similar_entries(target_dir, current_dir, 3);
    
    for (const auto& dir : similar) {
        suggestions.push_back("Did you mean 'cd " + dir + "'?");
    }
    
    // Common cd suggestions
    if (target_dir.find('/') == std::string::npos) {
        // Single directory name - suggest looking in common locations
        suggestions.push_back("Try 'ls' to see available directories.");
        if (target_dir != "..") {
            suggestions.push_back("Use 'cd ..' to go to parent directory.");
        }
    } else {
        // Path with slashes - suggest checking intermediate directories
        std::string parent_path = target_dir.substr(0, target_dir.find_last_of('/'));
        if (!parent_path.empty() && parent_path != target_dir) {
            suggestions.push_back("Check if '" + parent_path + "' exists first.");
        }
    }
    
    return suggestions;
}

std::vector<std::string> generate_ls_suggestions(const std::string& path,
                                                const std::string& current_dir) {
    std::vector<std::string> suggestions;
    
    // Extract directory and filename
    std::string directory = current_dir;
    std::string filename = path;
    
    size_t last_slash = path.find_last_of('/');
    if (last_slash != std::string::npos) {
        directory = path.substr(0, last_slash);
        filename = path.substr(last_slash + 1);
        if (directory.empty()) directory = "/";
    }
    
    // Find similar files/directories
    std::vector<std::string> similar = find_similar_entries(filename, directory, 3);
    
    for (const auto& item : similar) {
        if (last_slash != std::string::npos) {
            suggestions.push_back("Did you mean 'ls " + directory + "/" + item + "'?");
        } else {
            suggestions.push_back("Did you mean 'ls " + item + "'?");
        }
    }
    
    // General suggestions
    if (suggestions.empty()) {
        suggestions.push_back("Try 'ls' to see available files and directories.");
        if (path.find('/') != std::string::npos) {
            suggestions.push_back("Check if the directory path exists.");
        }
        suggestions.push_back("Use 'ls -la' to see hidden files.");
    }
    
    return suggestions;
}

int edit_distance(const std::string& str1, const std::string& str2) {
    const size_t m = str1.length();
    const size_t n = str2.length();
    
    if (m == 0) return n;
    if (n == 0) return m;
    
    std::vector<std::vector<int>> dp(m + 1, std::vector<int>(n + 1));
    
    for (size_t i = 0; i <= m; i++) dp[i][0] = i;
    for (size_t j = 0; j <= n; j++) dp[0][j] = j;
    
    for (size_t i = 1; i <= m; i++) {
        for (size_t j = 1; j <= n; j++) {
            if (str1[i - 1] == str2[j - 1]) {
                dp[i][j] = dp[i - 1][j - 1];
            } else {
                dp[i][j] = 1 + std::min({dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]});
            }
        }
    }
    
    return dp[m][n];
}

std::vector<std::string> find_similar_entries(const std::string& target_name,
                                             const std::string& directory,
                                             int max_suggestions) {
    std::vector<std::string> suggestions;
    
    try {
        std::vector<std::pair<int, std::string>> candidates;
        
        for (const auto& entry : std::filesystem::directory_iterator(directory)) {
            std::string name = entry.path().filename().string();
            
            // Skip hidden files starting with '.' unless target also starts with '.'
            if (name[0] == '.' && target_name[0] != '.') {
                continue;
            }
            
            int distance = edit_distance(target_name, name);
            
            // Only consider entries with reasonable similarity
            if (distance <= 3 && distance > 0) {
                candidates.emplace_back(distance, name);
            }
        }
        
        // Sort by edit distance (closest matches first)
        std::sort(candidates.begin(), candidates.end());
        
        // Add the best matches up to max_suggestions
        for (size_t i = 0; i < candidates.size() && i < static_cast<size_t>(max_suggestions); i++) {
            suggestions.push_back(candidates[i].second);
        }
        
    } catch (const std::filesystem::filesystem_error&) {
        // Directory doesn't exist or can't be read - no suggestions
    }
    
    return suggestions;
}

} // namespace suggestion_utils