name: Update Lines of Code Badge

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggering

# Add explicit permissions
permissions:
  contents: write

jobs:
  update-loc-badge:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Set a timeout to prevent hanging
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Only fetch the latest commit to speed up checkout

      - name: Count lines of code
        id: loc
        run: |
          # Install cloc tool
          sudo apt-get install -y cloc
          
          # Print start time for debugging
          echo "Starting cloc calculation at $(date)"
          
          # Count lines with more exclusions for better performance
          TOTAL_LINES=$(cloc . --exclude-dir=.git,.github,build,node_modules,dist,coverage --exclude-ext=json,lock --json | jq -r '.SUM.code')
          
          # Set output for later steps
          echo "total=$TOTAL_LINES" >> $GITHUB_OUTPUT
          
          # Display for debugging
          echo "Total lines of code: $TOTAL_LINES"
          echo "Finished cloc calculation at $(date)"

      - name: Update README badge
        run: |
          # Get the current lines of code count
          TOTAL_LINES="${{ steps.loc.outputs.total }}"
          
          echo "Updating README badge with $TOTAL_LINES lines of code"
          
          # Update both the number and change color to green
          sed -i "s|lines%20of%20code-[0-9]*-yellow|lines%20of%20code-${TOTAL_LINES}-green|g" README.md
          
          echo "README badge update completed"

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update lines of code count in README badge" || echo "No changes to commit"
          git push
