name: Update Lines of Code Badge

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight
  push:
    branches: [ master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-loc-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Count lines of code
        id: loc
        run: |
          # Install cloc tool
          sudo apt-get install -y cloc
          
          # Count lines excluding .git, .github, and other non-code directories
          TOTAL_LINES=$(cloc . --exclude-dir=.git,.github,build --json | jq -r '.SUM.code')
          
          # Set output for later steps
          echo "total=$TOTAL_LINES" >> $GITHUB_OUTPUT
          
          # Display for debugging
          echo "Total lines of code: $TOTAL_LINES"

      - name: Update README badge
        run: |
          # Get the current lines of code count
          TOTAL_LINES="${{ steps.loc.outputs.total }}"
          
          # Update the badge URL in the README with exact count
          sed -i "s|!\[Lines of Code\](https://img.shields.io/badge/lines%20of%20code-[0-9]*+-brightgreen)|![Lines of Code](https://img.shields.io/badge/lines%20of%20code-${TOTAL_LINES}-brightgreen)|g" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update lines of code count in README badge" || echo "No changes to commit"
          git push
